apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsaqw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsaqw
  template:
    metadata:
      labels:
        app: dsaqw
    spec:
      containers:
      - image: okteto.dev/dsaqw:latest
        name: dsaqw
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7e428a2d-53b2-4245-a38a-c7a3726ee1d7"
        - name: Vless_Path
          value: "/vl425"
        - name: Vmess_UUID
          value: "7e428a2d-53b2-4245-a38a-c7a3726ee1d7"
        - name: Vmess_Path
          value: "vm234"
        - name: Share_Path
          value: "/v2link"
